services:
    web:
        image: nginx:latest
        volumes:
            - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ..:/var/www/html
        ports:
            - 85:80
        restart: always
        depends_on:
            - php
            - db
    db:
      platform: linux/x86_64
      image: mysql:5.7
      restart: always
      environment:
        - MYSQL_DATABASE=${DATABASE_NAME}
        - MYSQL_USER=${DATABASE_USER}
        - MYSQL_PASSWORD=${DATABASE_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      shm_size: 1g
      ports:
        - 3306:3306
      expose:
        - 3306
      volumes:
        - db-data:/var/lib/mysql
    php:
        build: conf/php
        restart: always
        depends_on:
          - db
        volumes:
            - ./conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ..:/var/www/html


volumes:
    db-data:
